"""empty message

Revision ID: 275b165d199c
Revises: 
Create Date: 2025-05-09 17:33:19.938824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275b165d199c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_data',
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('avg_value', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('city')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city_data')
    # ### end Alembic commands ###
